<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>

    <!-- <OutputType>Exe</OutputType> -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTabletDriver.Plugin" Version="0.6.7"/>
    <PackageReference Include="OpenTabletDriver" Version="0.6.7"/>
    <Compile Remove="test.cs"/>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
  </PropertyGroup>
</Project>
